resources:
  - url: http://127.0.0.1:5000/flexispot-desk-card.js
    type: module
views:
  - cards:
      - type: custom:Flexispot-desk-card
        name: Flexispot Card Development
        entity: cover.desk
        test_gui: true
